<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1\Predicate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Predicate.NotExpr</code>
 */
class NotExpr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.osp.v1.Predicate child = 1;</code>
     */
    protected $child = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Osp\V1\Predicate $child
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate child = 1;</code>
     * @return \Osp\V1\Predicate
     */
    public function getChild()
    {
        return $this->child;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate child = 1;</code>
     * @param \Osp\V1\Predicate $var
     * @return $this
     */
    public function setChild($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate::class);
        $this->child = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NotExpr::class, \Osp\V1\Predicate_NotExpr::class);

