// Auto-generated by prost-build from proto/osp/v1/*.proto
// All four .proto files share `package osp.v1` so prost emits one module.
#[allow(clippy::all)]
#[allow(unknown_lints)]
pub mod osp_v1 {
    include!(concat!(env!("OUT_DIR"), "/osp.v1.rs"));
}

// Re-export under the names used by envelope.rs
pub use osp_v1 as frame;
pub use osp_v1 as auth;
pub use osp_v1 as common;
pub use osp_v1 as sync;
