<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/auth.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.AuthOk</code>
 */
class AuthOk extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>repeated string collection_scopes = 2;</code>
     */
    private $collection_scopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $collection_scopes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string collection_scopes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCollectionScopes()
    {
        return $this->collection_scopes;
    }

    /**
     * Generated from protobuf field <code>repeated string collection_scopes = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCollectionScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->collection_scopes = $arr;

        return $this;
    }

}

