<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/auth.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Auth</code>
 */
class Auth extends \Google\Protobuf\Internal\Message
{
    /**
     * JWT or opaque API key
     *
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *           JWT or opaque API key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * JWT or opaque API key
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * JWT or opaque API key
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

