<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/auth.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.AuthFailed</code>
 */
class AuthFailed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 1;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Osp\V1\ErrorInfo $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 1;</code>
     * @return \Osp\V1\ErrorInfo
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 1;</code>
     * @param \Osp\V1\ErrorInfo $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\ErrorInfo::class);
        $this->error = $var;

        return $this;
    }

}

