<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/common.proto

namespace Osp\V1;

use UnexpectedValueException;

/**
 * Capability negotiation
 *
 * Protobuf type <code>osp.v1.Capability</code>
 */
class Capability
{
    /**
     * Generated from protobuf enum <code>CAPABILITY_UNSPECIFIED = 0;</code>
     */
    const CAPABILITY_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>CAPABILITY_COMPRESSION_ZSTD = 1;</code>
     */
    const CAPABILITY_COMPRESSION_ZSTD = 1;
    /**
     * Generated from protobuf enum <code>CAPABILITY_CHUNKING = 2;</code>
     */
    const CAPABILITY_CHUNKING = 2;
    /**
     * Generated from protobuf enum <code>CAPABILITY_RESUME = 3;</code>
     */
    const CAPABILITY_RESUME = 3;
    /**
     * Generated from protobuf enum <code>CAPABILITY_PRESENCE = 4;</code>
     */
    const CAPABILITY_PRESENCE = 4;

    private static $valueToName = [
        self::CAPABILITY_UNSPECIFIED => 'CAPABILITY_UNSPECIFIED',
        self::CAPABILITY_COMPRESSION_ZSTD => 'CAPABILITY_COMPRESSION_ZSTD',
        self::CAPABILITY_CHUNKING => 'CAPABILITY_CHUNKING',
        self::CAPABILITY_RESUME => 'CAPABILITY_RESUME',
        self::CAPABILITY_PRESENCE => 'CAPABILITY_PRESENCE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

