<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/frame.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Envelope</code>
 */
class Envelope extends \Google\Protobuf\Internal\Message
{
    protected $payload;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Osp\V1\Hello $hello
     *           Auth / handshake
     *     @type \Osp\V1\HelloAck $hello_ack
     *     @type \Osp\V1\Auth $auth
     *     @type \Osp\V1\AuthOk $auth_ok
     *     @type \Osp\V1\AuthFailed $auth_failed
     *     @type \Osp\V1\Subscribe $subscribe
     *           Subscriptions
     *     @type \Osp\V1\Unsubscribe $unsubscribe
     *     @type \Osp\V1\SubscribeAck $subscribe_ack
     *     @type \Osp\V1\Operation $op
     *           Sync
     *     @type \Osp\V1\OpAck $op_ack
     *     @type \Osp\V1\SyncPush $sync_push
     *     @type \Osp\V1\SyncPullRequest $sync_pull_request
     *     @type \Osp\V1\SyncPullResponse $sync_pull_response
     *     @type \Osp\V1\Snapshot $snapshot
     *     @type \Osp\V1\Record $record
     *     @type \Osp\V1\ErrorInfo $error
     *           Misc
     *     @type \Osp\V1\Presence $presence
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Frame::initOnce();
        parent::__construct($data);
    }

    /**
     * Auth / handshake
     *
     * Generated from protobuf field <code>.osp.v1.Hello hello = 1;</code>
     * @return \Osp\V1\Hello
     */
    public function getHello()
    {
        return $this->readOneof(1);
    }

    /**
     * Auth / handshake
     *
     * Generated from protobuf field <code>.osp.v1.Hello hello = 1;</code>
     * @param \Osp\V1\Hello $var
     * @return $this
     */
    public function setHello($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Hello::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.HelloAck hello_ack = 2;</code>
     * @return \Osp\V1\HelloAck
     */
    public function getHelloAck()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.HelloAck hello_ack = 2;</code>
     * @param \Osp\V1\HelloAck $var
     * @return $this
     */
    public function setHelloAck($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\HelloAck::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Auth auth = 3;</code>
     * @return \Osp\V1\Auth
     */
    public function getAuth()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Auth auth = 3;</code>
     * @param \Osp\V1\Auth $var
     * @return $this
     */
    public function setAuth($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Auth::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.AuthOk auth_ok = 4;</code>
     * @return \Osp\V1\AuthOk
     */
    public function getAuthOk()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.AuthOk auth_ok = 4;</code>
     * @param \Osp\V1\AuthOk $var
     * @return $this
     */
    public function setAuthOk($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\AuthOk::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.AuthFailed auth_failed = 5;</code>
     * @return \Osp\V1\AuthFailed
     */
    public function getAuthFailed()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.AuthFailed auth_failed = 5;</code>
     * @param \Osp\V1\AuthFailed $var
     * @return $this
     */
    public function setAuthFailed($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\AuthFailed::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Subscriptions
     *
     * Generated from protobuf field <code>.osp.v1.Subscribe subscribe = 6;</code>
     * @return \Osp\V1\Subscribe
     */
    public function getSubscribe()
    {
        return $this->readOneof(6);
    }

    /**
     * Subscriptions
     *
     * Generated from protobuf field <code>.osp.v1.Subscribe subscribe = 6;</code>
     * @param \Osp\V1\Subscribe $var
     * @return $this
     */
    public function setSubscribe($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Subscribe::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Unsubscribe unsubscribe = 7;</code>
     * @return \Osp\V1\Unsubscribe
     */
    public function getUnsubscribe()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Unsubscribe unsubscribe = 7;</code>
     * @param \Osp\V1\Unsubscribe $var
     * @return $this
     */
    public function setUnsubscribe($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Unsubscribe::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.SubscribeAck subscribe_ack = 8;</code>
     * @return \Osp\V1\SubscribeAck
     */
    public function getSubscribeAck()
    {
        return $this->readOneof(8);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.SubscribeAck subscribe_ack = 8;</code>
     * @param \Osp\V1\SubscribeAck $var
     * @return $this
     */
    public function setSubscribeAck($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\SubscribeAck::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Sync
     *
     * Generated from protobuf field <code>.osp.v1.Operation op = 20;</code>
     * @return \Osp\V1\Operation
     */
    public function getOp()
    {
        return $this->readOneof(20);
    }

    /**
     * Sync
     *
     * Generated from protobuf field <code>.osp.v1.Operation op = 20;</code>
     * @param \Osp\V1\Operation $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Operation::class);
        $this->writeOneof(20, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.OpAck op_ack = 21;</code>
     * @return \Osp\V1\OpAck
     */
    public function getOpAck()
    {
        return $this->readOneof(21);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.OpAck op_ack = 21;</code>
     * @param \Osp\V1\OpAck $var
     * @return $this
     */
    public function setOpAck($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\OpAck::class);
        $this->writeOneof(21, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.SyncPush sync_push = 22;</code>
     * @return \Osp\V1\SyncPush
     */
    public function getSyncPush()
    {
        return $this->readOneof(22);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.SyncPush sync_push = 22;</code>
     * @param \Osp\V1\SyncPush $var
     * @return $this
     */
    public function setSyncPush($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\SyncPush::class);
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.SyncPullRequest sync_pull_request = 23;</code>
     * @return \Osp\V1\SyncPullRequest
     */
    public function getSyncPullRequest()
    {
        return $this->readOneof(23);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.SyncPullRequest sync_pull_request = 23;</code>
     * @param \Osp\V1\SyncPullRequest $var
     * @return $this
     */
    public function setSyncPullRequest($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\SyncPullRequest::class);
        $this->writeOneof(23, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.SyncPullResponse sync_pull_response = 24;</code>
     * @return \Osp\V1\SyncPullResponse
     */
    public function getSyncPullResponse()
    {
        return $this->readOneof(24);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.SyncPullResponse sync_pull_response = 24;</code>
     * @param \Osp\V1\SyncPullResponse $var
     * @return $this
     */
    public function setSyncPullResponse($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\SyncPullResponse::class);
        $this->writeOneof(24, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Snapshot snapshot = 25;</code>
     * @return \Osp\V1\Snapshot
     */
    public function getSnapshot()
    {
        return $this->readOneof(25);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Snapshot snapshot = 25;</code>
     * @param \Osp\V1\Snapshot $var
     * @return $this
     */
    public function setSnapshot($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Snapshot::class);
        $this->writeOneof(25, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Record record = 26;</code>
     * @return \Osp\V1\Record
     */
    public function getRecord()
    {
        return $this->readOneof(26);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Record record = 26;</code>
     * @param \Osp\V1\Record $var
     * @return $this
     */
    public function setRecord($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Record::class);
        $this->writeOneof(26, $var);

        return $this;
    }

    /**
     * Misc
     *
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 40;</code>
     * @return \Osp\V1\ErrorInfo
     */
    public function getError()
    {
        return $this->readOneof(40);
    }

    /**
     * Misc
     *
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 40;</code>
     * @param \Osp\V1\ErrorInfo $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\ErrorInfo::class);
        $this->writeOneof(40, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Presence presence = 41;</code>
     * @return \Osp\V1\Presence
     */
    public function getPresence()
    {
        return $this->readOneof(41);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Presence presence = 41;</code>
     * @param \Osp\V1\Presence $var
     * @return $this
     */
    public function setPresence($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Presence::class);
        $this->writeOneof(41, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getPayload()
    {
        return $this->whichOneof("payload");
    }

}

