<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.FieldMeta</code>
 */
class FieldMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 lamport = 1;</code>
     */
    protected $lamport = 0;
    /**
     * Generated from protobuf field <code>string writer_device_id = 2;</code>
     */
    protected $writer_device_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $lamport
     *     @type string $writer_device_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 lamport = 1;</code>
     * @return int|string
     */
    public function getLamport()
    {
        return $this->lamport;
    }

    /**
     * Generated from protobuf field <code>uint64 lamport = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLamport($var)
    {
        GPBUtil::checkUint64($var);
        $this->lamport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string writer_device_id = 2;</code>
     * @return string
     */
    public function getWriterDeviceId()
    {
        return $this->writer_device_id;
    }

    /**
     * Generated from protobuf field <code>string writer_device_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWriterDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writer_device_id = $var;

        return $this;
    }

}

