<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/common.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.FieldChange</code>
 */
class FieldChange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     */
    protected $field_name = '';
    /**
     * Generated from protobuf field <code>.osp.v1.Value new_value = 2;</code>
     */
    protected $new_value = null;
    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     */
    protected $lamport = 0;
    /**
     * UUID string
     *
     * Generated from protobuf field <code>string writer_device_id = 4;</code>
     */
    protected $writer_device_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field_name
     *     @type \Osp\V1\Value $new_value
     *     @type int|string $lamport
     *     @type string $writer_device_id
     *           UUID string
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Value new_value = 2;</code>
     * @return \Osp\V1\Value
     */
    public function getNewValue()
    {
        return $this->new_value;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Value new_value = 2;</code>
     * @param \Osp\V1\Value $var
     * @return $this
     */
    public function setNewValue($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Value::class);
        $this->new_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     * @return int|string
     */
    public function getLamport()
    {
        return $this->lamport;
    }

    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLamport($var)
    {
        GPBUtil::checkUint64($var);
        $this->lamport = $var;

        return $this;
    }

    /**
     * UUID string
     *
     * Generated from protobuf field <code>string writer_device_id = 4;</code>
     * @return string
     */
    public function getWriterDeviceId()
    {
        return $this->writer_device_id;
    }

    /**
     * UUID string
     *
     * Generated from protobuf field <code>string writer_device_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWriterDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writer_device_id = $var;

        return $this;
    }

}

