<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/auth.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Hello</code>
 */
class Hello extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 protocol_version = 1;</code>
     */
    protected $protocol_version = 0;
    /**
     * Generated from protobuf field <code>string sdk_version = 2;</code>
     */
    protected $sdk_version = '';
    /**
     * UUID v4
     *
     * Generated from protobuf field <code>string device_id = 3;</code>
     */
    protected $device_id = '';
    /**
     * "linux", "darwin", "android", "ios", "windows", "web", ...
     *
     * Generated from protobuf field <code>string device_platform = 4;</code>
     */
    protected $device_platform = '';
    /**
     * Generated from protobuf field <code>repeated .osp.v1.Capability capabilities = 5;</code>
     */
    private $capabilities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $protocol_version
     *     @type string $sdk_version
     *     @type string $device_id
     *           UUID v4
     *     @type string $device_platform
     *           "linux", "darwin", "android", "ios", "windows", "web", ...
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $capabilities
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 protocol_version = 1;</code>
     * @return int
     */
    public function getProtocolVersion()
    {
        return $this->protocol_version;
    }

    /**
     * Generated from protobuf field <code>uint32 protocol_version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProtocolVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->protocol_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sdk_version = 2;</code>
     * @return string
     */
    public function getSdkVersion()
    {
        return $this->sdk_version;
    }

    /**
     * Generated from protobuf field <code>string sdk_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->sdk_version = $var;

        return $this;
    }

    /**
     * UUID v4
     *
     * Generated from protobuf field <code>string device_id = 3;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * UUID v4
     *
     * Generated from protobuf field <code>string device_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * "linux", "darwin", "android", "ios", "windows", "web", ...
     *
     * Generated from protobuf field <code>string device_platform = 4;</code>
     * @return string
     */
    public function getDevicePlatform()
    {
        return $this->device_platform;
    }

    /**
     * "linux", "darwin", "android", "ios", "windows", "web", ...
     *
     * Generated from protobuf field <code>string device_platform = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDevicePlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.Capability capabilities = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCapabilities()
    {
        return $this->capabilities;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.Capability capabilities = 5;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCapabilities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Osp\V1\Capability::class);
        $this->capabilities = $arr;

        return $this;
    }

}

