<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/auth.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.HelloAck</code>
 */
class HelloAck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 protocol_version = 1;</code>
     */
    protected $protocol_version = 0;
    /**
     * Generated from protobuf field <code>string server_version = 2;</code>
     */
    protected $server_version = '';
    /**
     * UUID
     *
     * Generated from protobuf field <code>string session_id = 3;</code>
     */
    protected $session_id = '';
    /**
     * Generated from protobuf field <code>uint32 heartbeat_interval_ms = 4;</code>
     */
    protected $heartbeat_interval_ms = 0;
    /**
     * Generated from protobuf field <code>repeated .osp.v1.Capability selected_capabilities = 5;</code>
     */
    private $selected_capabilities;
    /**
     * number of recent ops server keeps in OpLogStore
     *
     * Generated from protobuf field <code>uint64 snapshot_window = 6;</code>
     */
    protected $snapshot_window = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $protocol_version
     *     @type string $server_version
     *     @type string $session_id
     *           UUID
     *     @type int $heartbeat_interval_ms
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $selected_capabilities
     *     @type int|string $snapshot_window
     *           number of recent ops server keeps in OpLogStore
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 protocol_version = 1;</code>
     * @return int
     */
    public function getProtocolVersion()
    {
        return $this->protocol_version;
    }

    /**
     * Generated from protobuf field <code>uint32 protocol_version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProtocolVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->protocol_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string server_version = 2;</code>
     * @return string
     */
    public function getServerVersion()
    {
        return $this->server_version;
    }

    /**
     * Generated from protobuf field <code>string server_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServerVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->server_version = $var;

        return $this;
    }

    /**
     * UUID
     *
     * Generated from protobuf field <code>string session_id = 3;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * UUID
     *
     * Generated from protobuf field <code>string session_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 heartbeat_interval_ms = 4;</code>
     * @return int
     */
    public function getHeartbeatIntervalMs()
    {
        return $this->heartbeat_interval_ms;
    }

    /**
     * Generated from protobuf field <code>uint32 heartbeat_interval_ms = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setHeartbeatIntervalMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->heartbeat_interval_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.Capability selected_capabilities = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSelectedCapabilities()
    {
        return $this->selected_capabilities;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.Capability selected_capabilities = 5;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSelectedCapabilities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Osp\V1\Capability::class);
        $this->selected_capabilities = $arr;

        return $this;
    }

    /**
     * number of recent ops server keeps in OpLogStore
     *
     * Generated from protobuf field <code>uint64 snapshot_window = 6;</code>
     * @return int|string
     */
    public function getSnapshotWindow()
    {
        return $this->snapshot_window;
    }

    /**
     * number of recent ops server keeps in OpLogStore
     *
     * Generated from protobuf field <code>uint64 snapshot_window = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSnapshotWindow($var)
    {
        GPBUtil::checkUint64($var);
        $this->snapshot_window = $var;

        return $this;
    }

}

