<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.OpAck</code>
 */
class OpAck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string op_id = 1;</code>
     */
    protected $op_id = '';
    /**
     * Generated from protobuf field <code>bool accepted = 2;</code>
     */
    protected $accepted = false;
    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 3;</code>
     */
    protected $error = null;
    /**
     * server-assigned revision, valid if accepted && kind != Delete
     *
     * Generated from protobuf field <code>uint64 revision = 4;</code>
     */
    protected $revision = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $op_id
     *     @type bool $accepted
     *     @type \Osp\V1\ErrorInfo $error
     *     @type int|string $revision
     *           server-assigned revision, valid if accepted && kind != Delete
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string op_id = 1;</code>
     * @return string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     * Generated from protobuf field <code>string op_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->op_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accepted = 2;</code>
     * @return bool
     */
    public function getAccepted()
    {
        return $this->accepted;
    }

    /**
     * Generated from protobuf field <code>bool accepted = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAccepted($var)
    {
        GPBUtil::checkBool($var);
        $this->accepted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 3;</code>
     * @return \Osp\V1\ErrorInfo
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 3;</code>
     * @param \Osp\V1\ErrorInfo $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\ErrorInfo::class);
        $this->error = $var;

        return $this;
    }

    /**
     * server-assigned revision, valid if accepted && kind != Delete
     *
     * Generated from protobuf field <code>uint64 revision = 4;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * server-assigned revision, valid if accepted && kind != Delete
     *
     * Generated from protobuf field <code>uint64 revision = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkUint64($var);
        $this->revision = $var;

        return $this;
    }

}

