<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Operation</code>
 */
class Operation extends \Google\Protobuf\Internal\Message
{
    /**
     * UUIDv7
     *
     * Generated from protobuf field <code>string op_id = 1;</code>
     */
    protected $op_id = '';
    /**
     * Generated from protobuf field <code>string device_id = 2;</code>
     */
    protected $device_id = '';
    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     */
    protected $lamport = 0;
    /**
     * Generated from protobuf field <code>string collection = 4;</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>string record_id = 5;</code>
     */
    protected $record_id = '';
    /**
     * Generated from protobuf field <code>.osp.v1.OpKind kind = 6;</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>repeated .osp.v1.FieldChange field_changes = 7;</code>
     */
    private $field_changes;
    /**
     * vector clock observed by writer when generating
     *
     * Generated from protobuf field <code>.osp.v1.VClock base_clock = 8;</code>
     */
    protected $base_clock = null;
    /**
     * Generated from protobuf field <code>uint64 timestamp_ms = 9;</code>
     */
    protected $timestamp_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $op_id
     *           UUIDv7
     *     @type string $device_id
     *     @type int|string $lamport
     *     @type string $collection
     *     @type string $record_id
     *     @type int $kind
     *     @type \Osp\V1\FieldChange[]|\Google\Protobuf\Internal\RepeatedField $field_changes
     *     @type \Osp\V1\VClock $base_clock
     *           vector clock observed by writer when generating
     *     @type int|string $timestamp_ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * UUIDv7
     *
     * Generated from protobuf field <code>string op_id = 1;</code>
     * @return string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     * UUIDv7
     *
     * Generated from protobuf field <code>string op_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->op_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_id = 2;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     * @return int|string
     */
    public function getLamport()
    {
        return $this->lamport;
    }

    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLamport($var)
    {
        GPBUtil::checkUint64($var);
        $this->lamport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection = 4;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string record_id = 5;</code>
     * @return string
     */
    public function getRecordId()
    {
        return $this->record_id;
    }

    /**
     * Generated from protobuf field <code>string record_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRecordId($var)
    {
        GPBUtil::checkString($var, True);
        $this->record_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.OpKind kind = 6;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.OpKind kind = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Osp\V1\OpKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.FieldChange field_changes = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldChanges()
    {
        return $this->field_changes;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.FieldChange field_changes = 7;</code>
     * @param \Osp\V1\FieldChange[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldChanges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Osp\V1\FieldChange::class);
        $this->field_changes = $arr;

        return $this;
    }

    /**
     * vector clock observed by writer when generating
     *
     * Generated from protobuf field <code>.osp.v1.VClock base_clock = 8;</code>
     * @return \Osp\V1\VClock
     */
    public function getBaseClock()
    {
        return $this->base_clock;
    }

    /**
     * vector clock observed by writer when generating
     *
     * Generated from protobuf field <code>.osp.v1.VClock base_clock = 8;</code>
     * @param \Osp\V1\VClock $var
     * @return $this
     */
    public function setBaseClock($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\VClock::class);
        $this->base_clock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp_ms = 9;</code>
     * @return int|string
     */
    public function getTimestampMs()
    {
        return $this->timestamp_ms;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp_ms = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestampMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp_ms = $var;

        return $this;
    }

}

