<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>osp.v1.OpKind</code>
 */
class OpKind
{
    /**
     * Generated from protobuf enum <code>OP_KIND_UNSPECIFIED = 0;</code>
     */
    const OP_KIND_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>OP_KIND_INSERT = 1;</code>
     */
    const OP_KIND_INSERT = 1;
    /**
     * Generated from protobuf enum <code>OP_KIND_UPDATE = 2;</code>
     */
    const OP_KIND_UPDATE = 2;
    /**
     * Generated from protobuf enum <code>OP_KIND_DELETE = 3;</code>
     */
    const OP_KIND_DELETE = 3;
    /**
     * Generated from protobuf enum <code>OP_KIND_RESTORE = 4;</code>
     */
    const OP_KIND_RESTORE = 4;

    private static $valueToName = [
        self::OP_KIND_UNSPECIFIED => 'OP_KIND_UNSPECIFIED',
        self::OP_KIND_INSERT => 'OP_KIND_INSERT',
        self::OP_KIND_UPDATE => 'OP_KIND_UPDATE',
        self::OP_KIND_DELETE => 'OP_KIND_DELETE',
        self::OP_KIND_RESTORE => 'OP_KIND_RESTORE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

