<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

if (false) {
    /**
     * This class is deprecated. Use Osp\V1\Predicate\Le instead.
     * @deprecated
     */
    class Predicate_Le {}
}
class_exists(Predicate\Le::class);
@trigger_error('Osp\V1\Predicate_Le is deprecated and will be removed in the next major release. Use Osp\V1\Predicate\Le instead', E_USER_DEPRECATED);

