<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

if (false) {
    /**
     * This class is deprecated. Use Osp\V1\Predicate\AndExpr instead.
     * @deprecated
     */
    class Predicate_AndExpr {}
}
class_exists(Predicate\AndExpr::class);
@trigger_error('Osp\V1\Predicate_AndExpr is deprecated and will be removed in the next major release. Use Osp\V1\Predicate\AndExpr instead', E_USER_DEPRECATED);

