<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

if (false) {
    /**
     * This class is deprecated. Use Osp\V1\Predicate\NotExpr instead.
     * @deprecated
     */
    class Predicate_NotExpr {}
}
class_exists(Predicate\NotExpr::class);
@trigger_error('Osp\V1\Predicate_NotExpr is deprecated and will be removed in the next major release. Use Osp\V1\Predicate\NotExpr instead', E_USER_DEPRECATED);

