<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

if (false) {
    /**
     * This class is deprecated. Use Osp\V1\Predicate\InExpr instead.
     * @deprecated
     */
    class Predicate_InExpr {}
}
class_exists(Predicate\InExpr::class);
@trigger_error('Osp\V1\Predicate_InExpr is deprecated and will be removed in the next major release. Use Osp\V1\Predicate\InExpr instead', E_USER_DEPRECATED);

