<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Predicate</code>
 */
class Predicate extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Osp\V1\Predicate\Eq $eq
     *     @type \Osp\V1\Predicate\Ne $ne
     *     @type \Osp\V1\Predicate\Lt $lt
     *     @type \Osp\V1\Predicate\Le $le
     *     @type \Osp\V1\Predicate\Gt $gt
     *     @type \Osp\V1\Predicate\Ge $ge
     *     @type \Osp\V1\Predicate\InExpr $in_expr
     *     @type \Osp\V1\Predicate\AndExpr $and_expr
     *     @type \Osp\V1\Predicate\OrExpr $or_expr
     *     @type \Osp\V1\Predicate\NotExpr $not_expr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Eq eq = 1;</code>
     * @return \Osp\V1\Predicate\Eq
     */
    public function getEq()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Eq eq = 1;</code>
     * @param \Osp\V1\Predicate\Eq $var
     * @return $this
     */
    public function setEq($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_Eq::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Ne ne = 2;</code>
     * @return \Osp\V1\Predicate\Ne
     */
    public function getNe()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Ne ne = 2;</code>
     * @param \Osp\V1\Predicate\Ne $var
     * @return $this
     */
    public function setNe($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_Ne::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Lt lt = 3;</code>
     * @return \Osp\V1\Predicate\Lt
     */
    public function getLt()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Lt lt = 3;</code>
     * @param \Osp\V1\Predicate\Lt $var
     * @return $this
     */
    public function setLt($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_Lt::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Le le = 4;</code>
     * @return \Osp\V1\Predicate\Le
     */
    public function getLe()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Le le = 4;</code>
     * @param \Osp\V1\Predicate\Le $var
     * @return $this
     */
    public function setLe($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_Le::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Gt gt = 5;</code>
     * @return \Osp\V1\Predicate\Gt
     */
    public function getGt()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Gt gt = 5;</code>
     * @param \Osp\V1\Predicate\Gt $var
     * @return $this
     */
    public function setGt($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_Gt::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Ge ge = 6;</code>
     * @return \Osp\V1\Predicate\Ge
     */
    public function getGe()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.Ge ge = 6;</code>
     * @param \Osp\V1\Predicate\Ge $var
     * @return $this
     */
    public function setGe($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_Ge::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.InExpr in_expr = 7;</code>
     * @return \Osp\V1\Predicate\InExpr
     */
    public function getInExpr()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.InExpr in_expr = 7;</code>
     * @param \Osp\V1\Predicate\InExpr $var
     * @return $this
     */
    public function setInExpr($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_InExpr::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.AndExpr and_expr = 8;</code>
     * @return \Osp\V1\Predicate\AndExpr
     */
    public function getAndExpr()
    {
        return $this->readOneof(8);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.AndExpr and_expr = 8;</code>
     * @param \Osp\V1\Predicate\AndExpr $var
     * @return $this
     */
    public function setAndExpr($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_AndExpr::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.OrExpr or_expr = 9;</code>
     * @return \Osp\V1\Predicate\OrExpr
     */
    public function getOrExpr()
    {
        return $this->readOneof(9);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.OrExpr or_expr = 9;</code>
     * @param \Osp\V1\Predicate\OrExpr $var
     * @return $this
     */
    public function setOrExpr($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_OrExpr::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.NotExpr not_expr = 10;</code>
     * @return \Osp\V1\Predicate\NotExpr
     */
    public function getNotExpr()
    {
        return $this->readOneof(10);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate.NotExpr not_expr = 10;</code>
     * @param \Osp\V1\Predicate\NotExpr $var
     * @return $this
     */
    public function setNotExpr($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate_NotExpr::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

