<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

if (false) {
    /**
     * This class is deprecated. Use Osp\V1\Predicate\Gt instead.
     * @deprecated
     */
    class Predicate_Gt {}
}
class_exists(Predicate\Gt::class);
@trigger_error('Osp\V1\Predicate_Gt is deprecated and will be removed in the next major release. Use Osp\V1\Predicate\Gt instead', E_USER_DEPRECATED);

