<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

if (false) {
    /**
     * This class is deprecated. Use Osp\V1\Predicate\Lt instead.
     * @deprecated
     */
    class Predicate_Lt {}
}
class_exists(Predicate\Lt::class);
@trigger_error('Osp\V1\Predicate_Lt is deprecated and will be removed in the next major release. Use Osp\V1\Predicate\Lt instead', E_USER_DEPRECATED);

