<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

if (false) {
    /**
     * This class is deprecated. Use Osp\V1\Predicate\Ne instead.
     * @deprecated
     */
    class Predicate_Ne {}
}
class_exists(Predicate\Ne::class);
@trigger_error('Osp\V1\Predicate_Ne is deprecated and will be removed in the next major release. Use Osp\V1\Predicate\Ne instead', E_USER_DEPRECATED);

