<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

if (false) {
    /**
     * This class is deprecated. Use Osp\V1\Predicate\Ge instead.
     * @deprecated
     */
    class Predicate_Ge {}
}
class_exists(Predicate\Ge::class);
@trigger_error('Osp\V1\Predicate_Ge is deprecated and will be removed in the next major release. Use Osp\V1\Predicate\Ge instead', E_USER_DEPRECATED);

