<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/auth.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PRESENCE: client announces its online state (see design §5.3, opcode 0x10).
 *
 * Generated from protobuf message <code>osp.v1.Presence</code>
 */
class Presence extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     */
    protected $device_id = '';
    /**
     * 0 = online, 1 = away, 2 = offline. v1: server logs only; broadcast is v1.1.
     *
     * Generated from protobuf field <code>uint32 status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     */
    protected $lamport = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_id
     *     @type int $status
     *           0 = online, 1 = away, 2 = offline. v1: server logs only; broadcast is v1.1.
     *     @type int|string $lamport
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * 0 = online, 1 = away, 2 = offline. v1: server logs only; broadcast is v1.1.
     *
     * Generated from protobuf field <code>uint32 status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * 0 = online, 1 = away, 2 = offline. v1: server logs only; broadcast is v1.1.
     *
     * Generated from protobuf field <code>uint32 status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     * @return int|string
     */
    public function getLamport()
    {
        return $this->lamport;
    }

    /**
     * Generated from protobuf field <code>uint64 lamport = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLamport($var)
    {
        GPBUtil::checkUint64($var);
        $this->lamport = $var;

        return $this;
    }

}

