<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Record</code>
 */
class Record extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>string record_id = 2;</code>
     */
    protected $record_id = '';
    /**
     * Generated from protobuf field <code>uint64 revision = 3;</code>
     */
    protected $revision = 0;
    /**
     * Generated from protobuf field <code>.osp.v1.VClock vector_clock = 4;</code>
     */
    protected $vector_clock = null;
    /**
     * Generated from protobuf field <code>bool tombstone = 5;</code>
     */
    protected $tombstone = false;
    /**
     * Generated from protobuf field <code>map<string, .osp.v1.Value> fields = 6;</code>
     */
    private $fields;
    /**
     * Generated from protobuf field <code>map<string, .osp.v1.FieldMeta> field_meta = 7;</code>
     */
    private $field_meta;
    /**
     * Generated from protobuf field <code>uint64 updated_at_ms = 8;</code>
     */
    protected $updated_at_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type string $record_id
     *     @type int|string $revision
     *     @type \Osp\V1\VClock $vector_clock
     *     @type bool $tombstone
     *     @type array|\Google\Protobuf\Internal\MapField $fields
     *     @type array|\Google\Protobuf\Internal\MapField $field_meta
     *     @type int|string $updated_at_ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string record_id = 2;</code>
     * @return string
     */
    public function getRecordId()
    {
        return $this->record_id;
    }

    /**
     * Generated from protobuf field <code>string record_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRecordId($var)
    {
        GPBUtil::checkString($var, True);
        $this->record_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 3;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkUint64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.VClock vector_clock = 4;</code>
     * @return \Osp\V1\VClock
     */
    public function getVectorClock()
    {
        return $this->vector_clock;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.VClock vector_clock = 4;</code>
     * @param \Osp\V1\VClock $var
     * @return $this
     */
    public function setVectorClock($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\VClock::class);
        $this->vector_clock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool tombstone = 5;</code>
     * @return bool
     */
    public function getTombstone()
    {
        return $this->tombstone;
    }

    /**
     * Generated from protobuf field <code>bool tombstone = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setTombstone($var)
    {
        GPBUtil::checkBool($var);
        $this->tombstone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .osp.v1.Value> fields = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>map<string, .osp.v1.Value> fields = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Osp\V1\Value::class);
        $this->fields = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .osp.v1.FieldMeta> field_meta = 7;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFieldMeta()
    {
        return $this->field_meta;
    }

    /**
     * Generated from protobuf field <code>map<string, .osp.v1.FieldMeta> field_meta = 7;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFieldMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Osp\V1\FieldMeta::class);
        $this->field_meta = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 updated_at_ms = 8;</code>
     * @return int|string
     */
    public function getUpdatedAtMs()
    {
        return $this->updated_at_ms;
    }

    /**
     * Generated from protobuf field <code>uint64 updated_at_ms = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAtMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->updated_at_ms = $var;

        return $this;
    }

}

