<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Snapshot</code>
 */
class Snapshot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>uint64 revision = 2;</code>
     */
    protected $revision = 0;
    /**
     * op_log_since(this) needed after snapshot
     *
     * Generated from protobuf field <code>uint64 lamport_floor = 3;</code>
     */
    protected $lamport_floor = 0;
    /**
     * Generated from protobuf field <code>repeated .osp.v1.Record records = 4;</code>
     */
    private $records;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type int|string $revision
     *     @type int|string $lamport_floor
     *           op_log_since(this) needed after snapshot
     *     @type \Osp\V1\Record[]|\Google\Protobuf\Internal\RepeatedField $records
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 2;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkUint64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * op_log_since(this) needed after snapshot
     *
     * Generated from protobuf field <code>uint64 lamport_floor = 3;</code>
     * @return int|string
     */
    public function getLamportFloor()
    {
        return $this->lamport_floor;
    }

    /**
     * op_log_since(this) needed after snapshot
     *
     * Generated from protobuf field <code>uint64 lamport_floor = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLamportFloor($var)
    {
        GPBUtil::checkUint64($var);
        $this->lamport_floor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.Record records = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.Record records = 4;</code>
     * @param \Osp\V1\Record[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Osp\V1\Record::class);
        $this->records = $arr;

        return $this;
    }

}

