<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Subscribe</code>
 */
class Subscribe extends \Google\Protobuf\Internal\Message
{
    /**
     * client-generated
     *
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     */
    protected $subscription_id = '';
    /**
     * Generated from protobuf field <code>string collection = 2;</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>.osp.v1.Predicate predicate = 3;</code>
     */
    protected $predicate = null;
    /**
     * 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 limit = 4;</code>
     */
    protected $limit = 0;
    /**
     * request latest snapshot on subscribe
     *
     * Generated from protobuf field <code>bool with_snapshot = 5;</code>
     */
    protected $with_snapshot = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subscription_id
     *           client-generated
     *     @type string $collection
     *     @type \Osp\V1\Predicate $predicate
     *     @type int $limit
     *           0 = unlimited
     *     @type bool $with_snapshot
     *           request latest snapshot on subscribe
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * client-generated
     *
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @return string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * client-generated
     *
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection = 2;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate predicate = 3;</code>
     * @return \Osp\V1\Predicate
     */
    public function getPredicate()
    {
        return $this->predicate;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.Predicate predicate = 3;</code>
     * @param \Osp\V1\Predicate $var
     * @return $this
     */
    public function setPredicate($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\Predicate::class);
        $this->predicate = $var;

        return $this;
    }

    /**
     * 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 limit = 4;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * 0 = unlimited
     *
     * Generated from protobuf field <code>uint32 limit = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * request latest snapshot on subscribe
     *
     * Generated from protobuf field <code>bool with_snapshot = 5;</code>
     * @return bool
     */
    public function getWithSnapshot()
    {
        return $this->with_snapshot;
    }

    /**
     * request latest snapshot on subscribe
     *
     * Generated from protobuf field <code>bool with_snapshot = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setWithSnapshot($var)
    {
        GPBUtil::checkBool($var);
        $this->with_snapshot = $var;

        return $this;
    }

}

