<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.SubscribeAck</code>
 */
class SubscribeAck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     */
    protected $subscription_id = '';
    /**
     * Generated from protobuf field <code>bool accepted = 2;</code>
     */
    protected $accepted = false;
    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 3;</code>
     */
    protected $error = null;
    /**
     * valid if with_snapshot && accepted
     *
     * Generated from protobuf field <code>uint64 snapshot_revision = 4;</code>
     */
    protected $snapshot_revision = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subscription_id
     *     @type bool $accepted
     *     @type \Osp\V1\ErrorInfo $error
     *     @type int|string $snapshot_revision
     *           valid if with_snapshot && accepted
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @return string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accepted = 2;</code>
     * @return bool
     */
    public function getAccepted()
    {
        return $this->accepted;
    }

    /**
     * Generated from protobuf field <code>bool accepted = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAccepted($var)
    {
        GPBUtil::checkBool($var);
        $this->accepted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 3;</code>
     * @return \Osp\V1\ErrorInfo
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ErrorInfo error = 3;</code>
     * @param \Osp\V1\ErrorInfo $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\ErrorInfo::class);
        $this->error = $var;

        return $this;
    }

    /**
     * valid if with_snapshot && accepted
     *
     * Generated from protobuf field <code>uint64 snapshot_revision = 4;</code>
     * @return int|string
     */
    public function getSnapshotRevision()
    {
        return $this->snapshot_revision;
    }

    /**
     * valid if with_snapshot && accepted
     *
     * Generated from protobuf field <code>uint64 snapshot_revision = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSnapshotRevision($var)
    {
        GPBUtil::checkUint64($var);
        $this->snapshot_revision = $var;

        return $this;
    }

}

