<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.SyncPullRequest</code>
 */
class SyncPullRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>uint64 since_lamport = 2;</code>
     */
    protected $since_lamport = 0;
    /**
     * Generated from protobuf field <code>uint32 max_ops = 3;</code>
     */
    protected $max_ops = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type int|string $since_lamport
     *     @type int $max_ops
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 since_lamport = 2;</code>
     * @return int|string
     */
    public function getSinceLamport()
    {
        return $this->since_lamport;
    }

    /**
     * Generated from protobuf field <code>uint64 since_lamport = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSinceLamport($var)
    {
        GPBUtil::checkUint64($var);
        $this->since_lamport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_ops = 3;</code>
     * @return int
     */
    public function getMaxOps()
    {
        return $this->max_ops;
    }

    /**
     * Generated from protobuf field <code>uint32 max_ops = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxOps($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_ops = $var;

        return $this;
    }

}

