<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.SyncPush</code>
 */
class SyncPush extends \Google\Protobuf\Internal\Message
{
    /**
     * Server → client: a batch of ops, possibly across collections
     *
     * Generated from protobuf field <code>repeated .osp.v1.Operation ops = 1;</code>
     */
    private $ops;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Osp\V1\Operation[]|\Google\Protobuf\Internal\RepeatedField $ops
     *           Server → client: a batch of ops, possibly across collections
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Server → client: a batch of ops, possibly across collections
     *
     * Generated from protobuf field <code>repeated .osp.v1.Operation ops = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOps()
    {
        return $this->ops;
    }

    /**
     * Server → client: a batch of ops, possibly across collections
     *
     * Generated from protobuf field <code>repeated .osp.v1.Operation ops = 1;</code>
     * @param \Osp\V1\Operation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Osp\V1\Operation::class);
        $this->ops = $arr;

        return $this;
    }

}

