<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/sync.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.SyncPullResponse</code>
 */
class SyncPullResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>uint64 since_lamport = 2;</code>
     */
    protected $since_lamport = 0;
    /**
     * Generated from protobuf field <code>repeated .osp.v1.Operation ops = 3;</code>
     */
    private $ops;
    /**
     * Generated from protobuf field <code>bool has_more = 4;</code>
     */
    protected $has_more = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type int|string $since_lamport
     *     @type \Osp\V1\Operation[]|\Google\Protobuf\Internal\RepeatedField $ops
     *     @type bool $has_more
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Sync::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 since_lamport = 2;</code>
     * @return int|string
     */
    public function getSinceLamport()
    {
        return $this->since_lamport;
    }

    /**
     * Generated from protobuf field <code>uint64 since_lamport = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSinceLamport($var)
    {
        GPBUtil::checkUint64($var);
        $this->since_lamport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.Operation ops = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOps()
    {
        return $this->ops;
    }

    /**
     * Generated from protobuf field <code>repeated .osp.v1.Operation ops = 3;</code>
     * @param \Osp\V1\Operation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Osp\V1\Operation::class);
        $this->ops = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool has_more = 4;</code>
     * @return bool
     */
    public function getHasMore()
    {
        return $this->has_more;
    }

    /**
     * Generated from protobuf field <code>bool has_more = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasMore($var)
    {
        GPBUtil::checkBool($var);
        $this->has_more = $var;

        return $this;
    }

}

