<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/common.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.Value</code>
 */
class Value extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $null_value
     *     @type bool $bool_value
     *     @type int|string $int_value
     *     @type float $double_value
     *     @type string $string_value
     *     @type string $bytes_value
     *     @type \Osp\V1\ValueArray $array_value
     *     @type \Osp\V1\ValueMap $object_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool null_value = 1;</code>
     * @return bool
     */
    public function getNullValue()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>bool null_value = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNullValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_value = 2;</code>
     * @return bool
     */
    public function getBoolValue()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>bool bool_value = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int_value = 3;</code>
     * @return int|string
     */
    public function getIntValue()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 int_value = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_value = 4;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>double double_value = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_value = 5;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>string string_value = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bytes_value = 6;</code>
     * @return string
     */
    public function getBytesValue()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>bytes bytes_value = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBytesValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ValueArray array_value = 7;</code>
     * @return \Osp\V1\ValueArray
     */
    public function getArrayValue()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ValueArray array_value = 7;</code>
     * @param \Osp\V1\ValueArray $var
     * @return $this
     */
    public function setArrayValue($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\ValueArray::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ValueMap object_value = 8;</code>
     * @return \Osp\V1\ValueMap
     */
    public function getObjectValue()
    {
        return $this->readOneof(8);
    }

    /**
     * Generated from protobuf field <code>.osp.v1.ValueMap object_value = 8;</code>
     * @param \Osp\V1\ValueMap $var
     * @return $this
     */
    public function setObjectValue($var)
    {
        GPBUtil::checkMessage($var, \Osp\V1\ValueMap::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

