<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osp/v1/common.proto

namespace Osp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>osp.v1.VClock</code>
 */
class VClock extends \Google\Protobuf\Internal\Message
{
    /**
     * device_id (UUID string) -> logical clock value
     *
     * Generated from protobuf field <code>map<string, uint64> entries = 1;</code>
     */
    private $entries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $entries
     *           device_id (UUID string) -> logical clock value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osp\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * device_id (UUID string) -> logical clock value
     *
     * Generated from protobuf field <code>map<string, uint64> entries = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getEntries()
    {
        return $this->entries;
    }

    /**
     * device_id (UUID string) -> logical clock value
     *
     * Generated from protobuf field <code>map<string, uint64> entries = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setEntries($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->entries = $arr;

        return $this;
    }

}

